version: "3.1"

services:

  scheduler:
    image: local/dask-sidecar:production
    hostname: dask-scheduler
    ports:
      - "8787:8787"
      - "8786:8786"
    volumes:
      - ./scheduler:/work
    command: ["dask-scheduler"]

  worker:
    image: local/dask-sidecar:production
    hostname: dask-worker
    volumes:
      - ./worker:/work
    environment:
      - PYTHONPATH=/work
    command: ["dask-worker", "tcp://scheduler:8786"]

  notebook:
    image: daskdev/dask-notebook
    hostname: notebook
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
    volumes:
      - ./notebook:/home/jovyan/work

  # ops
  portainer:
    image: portainer/portainer-ce
    hostname: portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


volumes:
  portainer_data: {}