version: "3.8"

services:

  scheduler:
    image: daskdev/dask
    hostname: dask-scheduler
    ports:
      # - "8786:8786" No need to expose
      # Exposes UI
      - "8787:8787"
    command: ["dask-scheduler"]
    volumes:
      - ./scheduler:/work
    working_dir: /work

  worker:
    image: daskdev/dask
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]
    volumes:
      - ./worker:/work
    environment:
      - PYTHONPATH=/work
    working_dir: /work
